# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.windowAviso = QtWidgets.QLabel(Form)
        self.windowAviso.setGeometry(QtCore.QRect(140, 10, 331, 131))
        self.windowAviso.setText("")
        self.windowAviso.setPixmap(QtGui.QPixmap("Imagenes/Aviso.png"))
        self.windowAviso.setObjectName("windowAviso")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 160, 151, 16))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(110, 190, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Form)
        self.buttonBox.accepted.connect(Form.accept)  # type: ignore
        self.buttonBox.rejected.connect(Form.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Quieres salir??"))
